services:
  ps-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ps-jaeger
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 5778:5778
      - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - PS-network
  ps-prometheus:
    image: prom/prometheus
    container_name: ps-prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - PS-network
  ps-grafana-alloy:
    image: grafana/alloy:latest
    container_name: ps-grafana-alloy
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./alloy/endpoints.json:/etc/alloy/endpoints.json
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    networks:
      - PS-network
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:${ALLOY_PORT}",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
  ps-grafana-loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - PS-network
  ps-grafana:
    image: grafana/grafana-oss
    container_name: ps-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - PS-network
    depends_on:
      - ps-prometheus
      - ps-grafana-alloy
  ps-localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - PS-network
volumes:
  grafana-storage: {}
  alloy-data: {}
  localstack: {}
networks:
  PS-network:
    driver: bridge